name: Container using KEY

on:
  workflow_dispatch:

jobs:
  do_some_actions_on_azure:
    runs-on: ubuntu-latest

    env:
      SA_NAME: ${{ secrets.SA_NAME }}
      SA_KEY1: ${{ secrets.SA_KEY1 }}
      
    steps:       
    - name: Create a container in Azure
      run: |
        TIME=$(date "+%H%M%S")
        az storage container create --name "key-$TIME" --account-name $SA_NAME --account-key $SA_KEY1 --auth-mode key
